### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1200]
```sh
$ npm test
...
 PASS  test/feed-queue.test.js
  ● Console

    console.error
      TypeError: Cannot read property 'id' of undefined
          at Queue.<anonymous> (/Users/humphd/repos/telescope/src/backend/lib/queue.js:77:54)
          at Queue.emit (events.js:315:20)
          at /Users/humphd/repos/telescope/node_modules/bull/lib/queue.js:819:19

      at node_modules/bull/lib/queue.js:559:22
```

Which is:

```js
      // The queue was paused
      logger.debug(`Queue ${name} resumed. ID:`, job.id);
    })
```

**Comment by humphd** [comment]
I also see it when I shut down the server:

```
TypeError: Cannot read property 'id' of undefined
    at Queue.<anonymous> (/Users/humphd/repos/telescope/src/backend/lib/queue.js:77:54)
    at Queue.emit (events.js:315:20)
    at /Users/humphd/repos/telescope/node_modules/bull/lib/queue.js:819:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async stopQueue (/Users/humphd/repos/telescope/src/backend/lib/shutdown.js:11:5)
    at async Promise.all (index 0)
    at async cleanShutdown (/Users/humphd/repos/telescope/src/backend/lib/shutdown.js:33:5)
    at async process.<anonymous> (/Users/humphd/repos/telescope/src/backend/lib/shutdown.js:61:5)
```

**Comment by humphd** [comment]
From @smilegodly on Slack

```
/usr/bin/node ./src/backend/index.js
[HPM] Proxy created: /  -> http://localhost:4000
node_modules/http-proxy-middleware/dist/logger.js:47
[HPM] Proxy rewrite rule created: "^/admin/build/status" ~> "/status"
node_modules/http-proxy-middleware/dist/logger.js:47
[HPM] Proxy created: /  -> http://localhost:4000
node_modules/http-proxy-middleware/dist/logger.js:47
[HPM] Proxy rewrite rule created: "^/admin/build/log" ~> "/log"
node_modules/http-proxy-middleware/dist/logger.js:47
TypeError: Cannot read property 'id' of undefined
    at Queue.<anonymous> (/home/smilegodly/gitStuff/telescope/src/backend/lib/queue.js:77:54)
    at Queue.emit (<node_internals>/events.js:314:20)
    at /home/smilegodly/gitStuff/telescope/node_modules/bull/lib/queue.js:819:19
    at async stopQueue (/home/smilegodly/gitStuff/telescope/src/backend/lib/shutdown.js:11:5)
    at async Promise.all (index 0)
    at async cleanShutdown (/home/smilegodly/gitStuff/telescope/src/backend/lib/shutdown.js:33:5)
    at async process.<anonymous> (/home/smilegodly/gitStuff/telescope/src/backend/lib/shutdown.js:61:5) {stack: 'TypeError: Cannot read property 'id' of undef…f/telescope/src/backend/lib/shutdown.js:61:5)', message: 'Cannot read property 'id' of undefined'}
node_modules/bull/lib/queue.js:559
No debugger available, can not send 'variables'
Process exited with code 1
```

**Comment by tonyvugithub** [comment]
@humphd : Is this still an issue? If it is, can I take over it?

**Comment by humphd** [comment]
Yes, it is.

Can I ask that you take 1 issue at a time, so we don't have people with multiple things assigned to them while others are looking for bugs to work on?

**Comment by tonyvugithub** [comment]
@humphd: certainly. I understand. I focus on the frontend testing first and come back to this if no one has not taken it yet.
