### ISSUE TITLE
[next] Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1354]
I pulled the `next` branch, ran `npm install` and then `npm run develop` and I get this:

```
$ npm run develop

> telescope-frontend@3.0.0 develop /Users/humphd/repos/telescope/src/frontend
> next dev -p 8000

Error: Cannot find module 'webpack'
Require stack:
- /Users/humphd/repos/telescope/src/frontend/node_modules/@next/react-dev-overlay/lib/middleware.js
- /Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/hot-reloader.js
- /Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/next-dev-server.js
- /Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/next.js
- /Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/lib/start-server.js
- /Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/cli/next-dev.js
- /Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/humphd/repos/telescope/src/frontend/node_modules/@next/react-dev-overlay/lib/middleware.js:69:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/humphd/repos/telescope/src/frontend/node_modules/@next/react-dev-overlay/lib/middleware.js',
    '/Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/hot-reloader.js',
    '/Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/next-dev-server.js',
    '/Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/next.js',
    '/Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/server/lib/start-server.js',
    '/Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/cli/next-dev.js',
    '/Users/humphd/repos/telescope/src/frontend/node_modules/next/dist/bin/next'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telescope-frontend@3.0.0 develop: `next dev -p 8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telescope-frontend@3.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/humphd/.npm/_logs/2020-11-14T21_41_44_483Z-debug.log
```

It looks like it's not installing dev dependencies?

**Comment by manekenpix** [comment]
I can't reproduce, `npm install` and then `npm run develop` works for me, I'm able to see the front-end.

**Comment by humphd** [comment]
Which version of node are you running?

**Comment by manekenpix** [comment]
```sh
$ node --version
v12.19.0
```
With [nvm](https://github.com/nvm-sh/nvm)

**Comment by manekenpix** [comment]
@c3ho were you able to get this front-end to run?

**Comment by c3ho** [comment]
Tested it ytd, was not able to get it to run. I tried blowing up the node_modules folder in both root directory and /src/frontend. Reinstalled modules and still didn't work.

**Comment by humphd** [comment]
I had to mess around with the inner `package.json` a bunch, switched to pinned versions vs. using `^` and blew away the lock and node_modules, and eventually it worked, but I have no idea what made it work.

**Comment by tonyvugithub** [comment]
@humphd : I was talking to @manekenpix  about this. I ran into the same problem. What I did was to have a completely fresh repo and there was no issue. There might be some conflict inside git that is hard to find out.

**Comment by cindyledev** [comment]
I hit this issue when the first Next PR was up and what worked for me was deleting the package-lock.json and npm install again

**Comment by humphd** [comment]
This is solved now.
