### ISSUE TITLE
Unable to run frontend tests via npm run release

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1422]
Running `npm run release` triggers our tests, and they die in the frontend tests with this error:

```
FAIL ./Spinner.test.js
  ● Test suite failed to run    [BABEL] /Users/humphd/repos/telescope/src/frontend/loadershim.js: `babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI. Set `NODE_ENV=test` to bypass, or run `gatsby build` first. (While processing: "/Users/humphd/repos/telescope/src/frontend/node_modules/babel-preset-gatsby/index.js")      at loadCachedConfig (node_modules/babel-preset-gatsby/index.js:26:15)
      at preset (node_modules/babel-preset-gatsby/index.js:42:29)
      at node_modules/@babel/core/lib/config/full.js:211:14
      at Function.<anonymous> (node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at Function.sync (node_modules/gensync/index.js:89:14)
      at sync (node_modules/@babel/core/lib/gensync-utils/async.js:66:25)
      at sync (node_modules/gensync/index.js:182:19)
```

I tried the recommended fixes above, and it doesn't work.  I'm going to disable them for now so I can release, and we'll have to turn them back on later.

**Comment by humphd** [comment]
Made two changes with this:

1. https://github.com/Seneca-CDOT/telescope/commit/af5fd8608688cb9982439a49cbc91f995aa7ba06
2. https://github.com/Seneca-CDOT/telescope/commit/592255dc15b153ea9ac79f63bd9e1c80cbf1ad28

**Comment by humphd** [comment]
cc @tonyvugithub

**Comment by humphd** [comment]
`npm run release` no longer exists, closing.
