### ISSUE TITLE
Error: Unable to parse elastic URL "http://elasticsearch:9200" and/or PORT "9200"

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1442]
I'm not able to run `docker-compose up --build` locally.  When I do, I get this error in Telescope:

```
telescope_1      | > node src/backend
telescope_1      |
telescope_1      | {"level":50,"time":1606086074314,"pid":17,"hostname":"a8951a77ddcd","error":{"input":"http://elasticsearch:9200:9200","code":"ERR_INVALID_URL"},"msg":"Unable to parse elastic URL \"http://elasticsearch:9200\" and/or PORT \"9200\""}
telescope_1      | /telescope/src/backend/lib/elastic.js:40
telescope_1      |     throw new Error(message);
telescope_1      |     ^
telescope_1      |
telescope_1      | Error: Unable to parse elastic URL "http://elasticsearch:9200" and/or PORT "9200"
telescope_1      |     at createElasticClient (/telescope/src/backend/lib/elastic.js:40:11)
telescope_1      |     at Object.<anonymous> (/telescope/src/backend/lib/elastic.js:48:11)
telescope_1      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
telescope_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
telescope_1      |     at Module.load (internal/modules/cjs/loader.js:928:32)
telescope_1      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
telescope_1      |     at Module.require (internal/modules/cjs/loader.js:952:19)
telescope_1      |     at require (internal/modules/cjs/helpers.js:88:18)
telescope_1      |     at Object.<anonymous> (/telescope/src/backend/utils/indexer.js:6:20)
telescope_1      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

It doesn't like http://elasticsearch:9200 as a URL (error code is `ERR_INVALID_URL`), which it's picking up from the `docker-compose.yml` file vs. my `.env`.

I think what's happening here is this:

```
> const { Client } = require('@elastic/elasticsearch');
> new Client({ node: 'http://elasticsearch:9200:9200' })
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL: http://elasticsearch:9200:9200
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at getUsernameAndPassword (/Users/humphd/repos/telescope/node_modules/@elastic/elasticsearch/index.js:263:38)
    at getAuth (/Users/humphd/repos/telescope/node_modules/@elastic/elasticsearch/index.js:253:16)
    at new Client (/Users/humphd/repos/telescope/node_modules/@elastic/elasticsearch/index.js:59:23)
    at REPL2:1:1
    at Script.runInThisContext (vm.js:132:18)
    at REPLServer.defaultEval (repl.js:484:29)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12) {
  input: 'http://elasticsearch:9200:9200',
  code: 'ERR_INVALID_URL'
}
```

If the URL includes the port, we double-include the port via this line in src/backend/lib/elastic.js:

```js
const elasticUrl = `${ELASTIC_URL}:${ELASTIC_PORT}` || 'http://localhost:9200';
```

We should figure out what we expect people to do in the `env` when we say URL vs. PORT.

**Comment by manekenpix** [comment]
This issue comes from [this commit](https://github.com/Seneca-CDOT/telescope/commit/cf8de79dd3570b9efd3db691b7896ebb8a30e262). It was possible to run Telescope using docker before this. The problem is the change in line 19:
```yml
- ELASTIC_URL=http://elasticsearch:${ELASTIC_PORT}
```

[`docker-compose-production.yml`](https://github.com/Seneca-CDOT/telescope/blob/7531ea5bbb3eb9f40d16b744e418ead6ca9afb69/docker-compose-production.yml#L28) has the correct value that we're currently using in `dev` and `prod` (and they're both up and running with no issues related to this). We should probably do the same in `docker-compose.yml`.

**Comment by humphd** [comment]
I don't think it's that commit; it probably came from my `MOCK_ELASTIC` change.

**Comment by manekenpix** [comment]
Sorry about that, I just edited my comment.
