### ISSUE TITLE
[Regression] npm run build fails with MDX about page in next.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1590]
After we landed #1463 we noticed that the `npm run build` command no longer completes, and seems to be related to the introduction of the MDX loader?

For now, we'll revert.

Here's the STR and log:

```
$ npm run build

> telescope-frontend@3.0.0 build /Users/humphd/repos/telescope/src/frontend/next
> next build && next export

Copying API_URL=https://dev.telescope.cdot.systems to NEXT_PUBLIC_API_URL
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Finalizing page optimization

Page                                                           Size     First Load JS
┌ ○ /                                                          34.6 kB         112 kB
├   /_app                                                      0 B            77.4 kB
├ ○ /404                                                       3.44 kB        80.9 kB
└ ○ /about                                                     3.16 kB        80.6 kB
+ First Load JS shared by all                                  77.4 kB
  ├ chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.7379a5.js  9.29 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.102826.js  12.7 kB
  ├ chunks/framework.984a54.js                                 40.2 kB
  ├ chunks/main.e3e27e.js                                      6.46 kB
  ├ chunks/pages/_app.19db35.js                                7.99 kB
  ├ chunks/webpack.e06743.js                                   751 B
  └ css/c82da33a2f2d8e065f82.css                               1.04 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

[=   ] info  - Generating static pages (0/3)Copying API_URL=https://dev.telescope.cdot.systems to NEXT_PUBLIC_API_URL
info  - using build directory: /Users/humphd/repos/telescope/src/frontend/next/out
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 3 workers
info  - Copying "public" directory
[=== ] info  - Exporting (0/3)
Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
Error: Cannot find module '/Users/humphd/repos/telescope/src/frontend/next/out/server/pages-manifest.json'
Require stack:
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/load-components.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/api-utils.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/render.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/worker.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getPagePath (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at Object.exportPage [as default] (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/worker.js:15:215)

Error occurred prerendering page "/about". Read more: https://err.sh/next.js/prerender-error
Error: Cannot find module '/Users/humphd/repos/telescope/src/frontend/next/out/server/pages-manifest.json'
Require stack:
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/load-components.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/api-utils.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/render.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/worker.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getPagePath (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at Object.exportPage [as default] (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/worker.js:15:215)

Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
Error: Cannot find module '/Users/humphd/repos/telescope/src/frontend/next/out/server/pages-manifest.json'
Require stack:
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/load-components.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/api-utils.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/render.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/worker.js
- /Users/humphd/repos/telescope/src/frontend/next/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getPagePath (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js:1:657)
    at requirePage (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/require.js:1:1062)
    at loadComponents (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/next-server/server/load-components.js:1:807)
    at Object.exportPage [as default] (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/worker.js:15:215)
Error: Export encountered errors on following paths:
	/
	/404
	/about
    at exportApp (/Users/humphd/repos/telescope/src/frontend/next/node_modules/next/dist/export/index.js:30:1103)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[    ] info  - Exporting (0/3)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telescope-frontend@3.0.0 build: `next build && next export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telescope-frontend@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/humphd/.npm/_logs/2021-01-22T19_33_58_437Z-debug.log
```

**Comment by cindyledev** [comment]
I was able to reproduce this issue locally. Getting rid of the `distDir: 'out'` line in 
`module.exports = withMDX({ ... });` seems to solve this problem. What was `distDir` supposed to do anyway?

**Comment by chrispinkney** [comment]
> 
> 
> I was able to reproduce this issue locally. Getting rid of the `distDir: 'out'` line in
> `module.exports = withMDX({ ... });` seems to solve this problem. What was `distDir` supposed to do anyway?

See [this](https://github.com/Seneca-CDOT/telescope/pull/1487#discussion_r561531250). 

@raygervais @humphd given that running `npm run build:next` already runs `next build && next export`, which according to [this](https://nextjs.org/docs/advanced-features/static-html-export#how-to-use-it) already outputs to an `/out` folder, can we not just drop the `distDir` all together?

**Comment by cindyledev** [comment]
> > I was able to reproduce this issue locally. Getting rid of the `distDir: 'out'` line in
> > `module.exports = withMDX({ ... });` seems to solve this problem. What was `distDir` supposed to do anyway?
> 
> @cindyledev Hahaha, see [this](https://github.com/Seneca-CDOT/telescope/pull/1487#discussion_r561531250). 😆
> 
> @raygervais @humphd given that running `npm run build:next` already runs `next build && next export`, which according to [this](https://nextjs.org/docs/advanced-features/static-html-export#how-to-use-it) already outputs to an `/out` folder, can we not just drop the `distDir` all together?

When I ran `npm run build` everything outputs to the /out folder as expected. Can you submit a PR without the distDir line so I can review the PR? It works on my machine but I wanna make sure that it will work on Netlify PR preview
