### ISSUE TITLE
Vercel Builds breaking with invalid URL /

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2102]
Just saw this: https://vercel.com/humphd/telescope/J7Xv4iXm83fRpVDt5m8DFGFZ67TK.  This might be due to a recent change I made to how the errors page renders things:

```
Error occurred prerendering page "/error". Read more: https://nextjs.org/docs/messages/prerender-error
--
14:52:23.467 | TypeError [ERR_INVALID_URL]: Invalid URL: /
14:52:23.468 | at onParseError (internal/url.js:259:9)
14:52:23.468 | at parse (<anonymous>)
14:52:23.468 | at new URL (internal/url.js:335:5)
14:52:23.468 | at new URL (internal/url.js:332:22)
14:52:23.468 | at ErrorPage (/vercel/workpath0/.next/server/pages/error.js:227:20)
14:52:23.468 | at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
14:52:23.468 | at bb (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
14:52:23.468 | at a.b.render (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
14:52:23.468 | at a.b.read (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
14:52:23.468 | at exports.renderToString (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
```

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/commit/58889396a79060c3dee3b92ab48acb98b03e9b6a#diff-997279ffac847601ce3ddc824cb36cc031a13dc02edd2f82c9955192c0e8f452R15
