### ISSUE TITLE
Telescope fails to build the front-end when deployed with docker

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#2230]
Telescope fails to to build the front-end in the staging and production servers:

```sh
info  - Creating an optimized production build...
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /telescope/src/web/node_modules/next-pwa/register.js
> [PWA] Service worker: /telescope/src/web/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
> [PWA] Compile server
Failed to compile.

./node_modules/@fontsource/pt-serif/index.css
TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Array.map (<anonymous>)
    at runMicrotasks (<anonymous>)
    at runMicrotasks (<anonymous>)


> Build error occurred
Error: > Build failed because of webpack errors
    at /telescope/src/web/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (/telescope/src/web/node_modules/next/dist/telemetry/trace/trace.js:6:584)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @senecacdot/telescope-frontend@3.0.0 build: `next build && next export`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @senecacdot/telescope-frontend@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-10T06_12_35_097Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @senecacdot/telescope@2.0.0 build: `npm run build --prefix src/web --`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @senecacdot/telescope@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-10T06_12_35_117Z-debug.log
ERROR: Service 'telescope' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

@tonyvugithub

**Comment by manekenpix** [comment]
@HyperTHD @PedroFonsecaDEV @yuanLeeMidori @DukeManh

**Comment by humphd** [comment]
What does bumping https://github.com/Seneca-CDOT/telescope/blob/master/src/web/package.json#L25 to 5.2.21 do?  I see other people getting this same error, which I suspect is in a downstream auto-prefixer dependency.

**Comment by manekenpix** [comment]
This no longer happens, the front-end gets built on the staging and production servers for every new deployment.
