### ISSUE TITLE
Test failures on Travis with test/github.test.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#225]
I'm seeing this a bunch, only on Travis (e.g., https://travis-ci.org/Seneca-CDOT/telescope/builds/612600779#L231):

```
 ● test fetching data for a valid repository URL
    TypeError: Cannot read property 'avatar_url' of undefined
      94 |       } else if (ghUrl.branch === 'master') {
      95 |         const {
    > 96 |           owner: { avatar_url: avatarURL },
         |                                ^
      97 |           description,
      98 |           license,
      99 |           open_issues: openIssues,
      at src/github-url.js:96:32
      at Object.<anonymous> (test/github.test.js:45:16)
  ● test fetching data for a valid issue URL
    TypeError: Cannot read property 'login' of undefined
      116 |       } else {
      117 |         const {
    > 118 |           user: { login, avatar_url: avatarURL },
          |                   ^
      119 |           body,
      120 |           created_at: createdAt,
      121 |         } = data;
      at src/github-url.js:118:19
      at Object.<anonymous> (test/github.test.js:64:17)
  ● test fetching data for a valid pull request URL
    TypeError: Cannot read property 'login' of undefined
      116 |       } else {
      117 |         const {
    > 118 |           user: { login, avatar_url: avatarURL },
          |                   ^
      119 |           body,
      120 |           created_at: createdAt,
      121 |         } = data;
      at src/github-url.js:118:19
      at Object.<anonymous> (test/github.test.js:84:14)
```

I wonder if we need to add a token to Travis' environment?  I wonder if we're hitting rate limiting from the Travis IP?

This might also get fixed with #208. 

cc @manekenpix

**Comment by humphd** [comment]
@manekenpix one short term fix would be to disable these tests until we have a fix, so you buy yourself more time.  People are getting the failures and don't understand, and I don't want to rush you.

**Comment by manekenpix** [comment]
@humphd I think disable the tests is the best solution. I'll probably have a fix tomorrow. Are you going to disable them on Travis or should I do something on my side?

**Comment by humphd** [comment]
We have to disable just these tests, switch `test()` to `test.skip()` in your file in a PR, and we'll merge it.
