### ISSUE TITLE
Cannot find module '../lib' from 'src/web/node_modules/react-icons/fa/index.js'

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2324]
After landing @DukeManh's recent PR, we're failing on `master` with:

```
FAIL src/web/src/components/AboutFooter.test.tsx
  ● Test suite failed to run

    Cannot find module '../lib' from 'src/web/node_modules/react-icons/fa/index.js'

    Require stack:
      src/web/node_modules/react-icons/fa/index.js
      src/web/src/components/AboutFooter.tsx
      src/web/src/components/AboutFooter.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/web/node_modules/react-icons/fa/index.js:2:15)

  console.warn
PASS src/web/src/components/Logo.test.tsx
  ✓ renders correctly (23 ms)

    Material-UI: The `css` function is deprecated. Use the `styleFunctionSx` instead.

      at css (src/web/node_modules/@material-ui/system/styleFunctionSx.js:75:13)
      at Object.<anonymous> (src/web/node_modules/@material-ui/core/Box/Box.js:14:37)
      at Object.<anonymous> (src/web/node_modules/@material-ui/core/Box/index.js:21:36)

Summary of all failing tests
FAIL src/web/src/components/AboutFooter.test.tsx
  ● Test suite failed to run

    Cannot find module '../lib' from 'src/web/node_modules/react-icons/fa/index.js'

    Require stack:
      src/web/node_modules/react-icons/fa/index.js
      src/web/src/components/AboutFooter.tsx
      src/web/src/components/AboutFooter.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/web/node_modules/react-icons/fa/index.js:2:15)
```

I don't think they are related, but I don't understand this either.

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/runs/3778501984.  I've re-triggered the builds.

**Comment by humphd** [comment]
Looks like upstream breakage: https://github.com/react-icons/react-icons/issues/490
