### ISSUE TITLE
Material-UI: The `css` function is deprecated. Use the `styleFunctionSx` instead.

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2325]
Seen in our tests:

```
Material-UI: The `css` function is deprecated. Use the `styleFunctionSx` instead.

      at css (src/web/node_modules/@material-ui/system/styleFunctionSx.js:75:13)
      at Object.<anonymous> (src/web/node_modules/@material-ui/core/Box/Box.js:14:37)
      at Object.<anonymous> (src/web/node_modules/@material-ui/core/Box/index.js:21:36)
```

We should investigate what's going on with our use of `css()` and update if necessary.

**Comment by rheimon1** [comment]
hello, @humphd ! Can you assign it to me?

**Comment by humphd** [comment]
@rheimon1 sure, you can go ahead.
