### ISSUE TITLE
Supabase auth crashing in supabase/gotrue container, missing supabaseUrl

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2836]
When I start the docker services (`pnpm services:start`) and look at the running containers, I notice that the `supabase/gotrue` container is restarting.  Looking at its logs I see:

```
Error: supabaseUrl is required.
    at new SupabaseClient (/app/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:50:19)
    at createClient (/app/node_modules/@supabase/supabase-js/dist/main/index.js:25:12)
    at Object.<anonymous> (/app/src/supabase.js:7:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/src/middleware.js:4:18)
{"level":30,"time":1643997153065,"pid":9,"hostname":"722331e2fe83","env":{"GOTRUE_JWT_DEFAULT_GROUP_NAME":"authenticated","NODE_VERSION":"16.13.2","HOSTNAME":"722331e2fe83","GOTRUE_MAILER_URLPATHS_CONFIRMATION":"/auth/v1/verify","YARN_VERSION":"1.22.15","HOME":"/home/node","GOTRUE_SITE_URL":"http://localhost:8000","GOTRUE_DB_DRIVER":"postgres","GOTRUE_SMTP_ADMIN_EMAIL":"admin@example.com","GOTRUE_SMTP_PASS":"fake_mail_password","GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE":"/auth/v1/verify","GOTRUE_JWT_EXP":"3600","GOTRUE_EXTERNAL_PHONE_ENABLED":"false","GOTRUE_SMTP_HOST":"mail","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","GOTRUE_SMTP_USER":"fake_mail_user","GOTRUE_URI_ALLOW_LIST":"","GOTRUE_DB_DATABASE_URL":"postgres://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres?search_path=auth","GOTRUE_SMTP_PORT":"2500","GOTRUE_SMTP_SENDER_NAME":"fake_sender","GOTRUE_MAILER_URLPATHS_INVITE":"/auth/v1/verify","GOTRUE_API_HOST":"0.0.0.0","GOTRUE_SMS_AUTOCONFIRM":"false","PWD":"/app","GOTRUE_MAILER_URLPATHS_RECOVERY":"/auth/v1/verify","GOTRUE_MAILER_AUTOCONFIRM":"true","GOTRUE_DISABLE_SIGNUP":"false","GOTRUE_API_PORT":"9999","GOTRUE_EXTERNAL_EMAIL_ENABLED":"true","GOTRUE_JWT_SECRET":"your-super-secret-jwt-token-with-at-least-32-characters-long"},"msg":"Auth env"}
{ SERVICE_ROLE_KEY: undefined, SUPABASE_API_URL: undefined } env
/app/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:50
            throw new Error('supabaseUrl is required.');
```

It looks like we aren't setting the `SERVICE_ROLE_KEY` and `SUPABASE_API_URL` in some part of our code where it's expected.

**Comment by DukeManh** [comment]
The problem is gone after I rebuild the SSO service, I bet I was because I changed the env var from `SUPABASE_API_URL` to `SUPABASE_URL`.

**Comment by humphd** [comment]
I removed all the sso/auth images locally, and rebuilt.  It still happens the same way for me.  What am I missing?

**Comment by humphd** [comment]
OK, I got it.  I didn't blow away the gotrue container.

I looked at the other services' logs, and this one is interesting too from `supabase/storage-api`:

```
(node:8) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 172.21.0.8:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(Use `storage-api-x86_64 --trace-warnings ...` to show where the warning was created)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
running migrations
finished migrations
[1644014471290] INFO (8 on 57ee5c37962b): Server listening at http://0.0.0.0:5000
Server listening at http://0.0.0.0:5000
```

They have some kind of a bug that we could help fix.
