### ISSUE TITLE
Configure ESLint for Docusaurus sub-project

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#2970]
Related to #2965 

After #2862, a number of ESLint errors showed up in the Docusaurus files. Eg

```
Parsing error: The keyword 'const' is reserved
```

**Comment by humphd** [comment]
I think that VSCode can't find our .eslintrc file anymore (after we moved it to the sub-project), and so it's using the wrong version of ECMAScript.

**Comment by humphd** [comment]
cc @TueeNguyen, who complained of this today too.

I'm also hitting it.

**Comment by TueeNguyen** [comment]
I've added this and the complain went away

![image](https://user-images.githubusercontent.com/58532267/154611394-3b159f1b-e69a-42e7-868d-d6cff7c54d48.png)

**Comment by DukeManh** [comment]
This stops me from doing any work with VSCode. I think it'll be best to reverse #2862, which caused it, and merge it again when we have a fix.

**Comment by DukeManh** [comment]
Or we can reverse the eslint config locally to avoid this.

**Comment by humphd** [comment]
![image](https://user-images.githubusercontent.com/427398/154765496-0d688571-3320-4f57-9aca-3dfced161ad3.png)

What I think is happening here is that the vscode extension is being thrown off by not finding an eslint config.  We might need to put it in the root of all our packages.

**Comment by humphd** [comment]
I also notice when I go into `src/web` and click on a JS file:

```
(node:89107) UnhandledPromiseRejectionWarning: Error: Failed to load config "eslint-config-telescope" to extend from.
Referenced from: /Users/humphd/repos/telescope/src/web/.eslintrc.js
    at configInvalidError (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/humphd/repos/telescope/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
(node:89107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 37)
```

I think `extends: 'eslint-config-telescope'` has to be `extends: '@senecacdot/eslint-config-telescope'` everywhere (e.g., `src/web/.eslintrc.js). cc @tcvan0707, @Meneguini

And we need that same file in all of our sub-packages.
