### ISSUE TITLE
bug: Error options.uri is a required argument

### ISSUE THREAD

**Issue by ragnarokatz** [Seneca-CDOT/telescope#299]
OS: Ubuntu 18.04
node -v v10.17.0
npm -v 6.11.3

**Reproducibility: Only happens sometimes**

Steps to reproduce:
`docker-compose up -d redis`
`npm start`

Ctrl+C to stop
Leave docker+ redis running for a while, then

`npm start`
gives:
```
Telescope listening on port 3000
Enqueuing Job - https://neilong31.wordpress.com/feed/
Enqueuing Job - http://ajhooper.blogspot.com/feeds/posts/default
Enqueuing Job - http://ljubomirgorscak.blogspot.com/feeds/posts/default
Enqueuing Job - http://nashutzu.blogspot.com/feeds/posts/default
Enqueuing Job - http://nadavid.blogspot.com/feeds/posts/default
Enqueuing Job - http://gkrilov.blogspot.com/feeds/posts/default
Enqueuing Job - http://KrazyDre.blogspot.com/feeds/posts/default?alt=rss
Enqueuing Job - http://dcucereavii.blogspot.com/feeds/posts/default?alt=rss
UNHANDLED REJECTION:  Shutting down...
Error options.uri is a required argument
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telescope@0.0.1 start: `node src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telescope@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have attached the complete log of this run as well, found in npm's logs folder:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle telescope@0.0.1~prestart: telescope@0.0.1
6 info lifecycle telescope@0.0.1~start: telescope@0.0.1
7 verbose lifecycle telescope@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle telescope@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/hightemplar/telescope/node_modules/.bin:/home/hightemplar/miniconda3/envs/python37/bin:/home/hightemplar/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle telescope@0.0.1~start: CWD: /home/hightemplar/telescope
10 silly lifecycle telescope@0.0.1~start: Args: [ '-c', 'node src' ]
11 silly lifecycle telescope@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle telescope@0.0.1~start: Failed to exec start script
13 verbose stack Error: telescope@0.0.1 start: `node src`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid telescope@0.0.1
15 verbose cwd /home/hightemplar/telescope
16 verbose Linux 5.0.0-36-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.17.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error telescope@0.0.1 start: `node src`
22 error Exit status 1
23 error Failed at the telescope@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by humphd** [comment]
Fixed by https://github.com/Seneca-CDOT/telescope/pull/288, just waiting on reviews to land.  @ragnarokatz can you review?

**Comment by ragnarokatz** [comment]
@humphd it looks fixed on my end. closing this ticket. thank you.
