### ISSUE TITLE
Test failure: TypeError: logger.debug is not a function

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#305]
I think the way `logger` is being [exported](https://github.com/Seneca-CDOT/telescope/pull/278/files#diff-339e40296231835cde0cae0efe2af447R49) after the change in #278 has changed, breaking this.

```
FAIL  test/storage.test.js
  ● Test suite failed to run

    TypeError: logger.debug is not a function

      19 | // If using MockRedis, shim info() until https://github.com/stipsan/ioredis-mock/issues/841 ships
      20 | if (useMockRedis && typeof MockRedis.prototype.info !== 'function') {
    > 21 |   logger.debug('Shimming MockRedis info() method');
         |          ^
      22 |   MockRedis.prototype.info = () => Promise.resolve('redis_version:999.999.999');
      23 | }
      24 | 

      at Object.<anonymous> (src/lib/redis.js:21:10)
      at Object.<anonymous> (src/storage.js:1:19)
```

cc @miggs125, @hansal7014

**Comment by humphd** [comment]
Whoever fixes this should also add regression tests for `logger.js`, such that we check to see that all the methods we call on it, e.g., `debug()`, exist and are in fact functions.
