### ISSUE TITLE
Turbo Server Token secret not being passed correctly

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3466]
I notice the turbo cache isn't working properly (cc @menghif)

```
Post job cleanup.
Found server pid: [2](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:2)100
Server with pid: 2100 is not running
There is nothing to upload.
Server logs:
Error: Input required and not supplied: server-token
    at getInput (D:\a\_actions\felixmosh\turborepo-gh-artifacts\v1\dist\turboServer\index.js:216:15)
    at startServer (D:\a\_actions\felixmosh\turborepo-gh-artifacts\v1\dist\turboServer\index.js:28899:42)
    at D:\a\_actions\felixmosh\turborepo-gh-artifacts\v1\dist\turboServer\index.js:2895[3](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:3):1
    at D:\a\_actions\felixmosh\turborepo-gh-artifacts\v1\dist\turboServer\index.js:28958:3
    at Object.<anonymous> (D:\a\_actions\felixmosh\turborepo-gh-artifacts\v1\dist\turboServer\index.js:28961:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:1[4](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:4))
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:9[5](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:5)0:32)
    at Function.Module._load (internal/modules/cjs/loader.js:[7](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:7)[9](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:9)0:[12](https://github.com/Seneca-CDOT/telescope/runs/5992730435?check_suite_focus=true#step:9:12))
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
```

**Comment by humphd** [comment]
What we're doing looks right to me, I'm not sure why this isn't going through...
