### ISSUE TITLE
Investigate DOMPurify and JSDOM issues in HTML sanitizer

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#352]
In #344 we applied a bandaid fix to a seemingly larger problem: our HTML sanitizer uses DOMPurifier and JSDOM in such a way that certain HTML can cause it to throw.  Specifically, anything that requires a resource to be loaded (e.g., `<img src>`).

We need to get this working in a way we can count on.  Ideas to investigate:

- version issues with JSDOM and DOMPurify, see https://github.com/Seneca-CDOT/telescope/issues/343#issuecomment-558363444
- the way we create our document from snippets, see https://github.com/Seneca-CDOT/telescope/issues/343#issuecomment-557930403

It could also be something else.  DOMPurify is able to pass their unit tests using JSDOM, and doing almost the same thing we were doing when we failed, see https://github.com/cure53/DOMPurify/blob/3bc348bf5882b200e559f65f3fc749733afb812d/test/bootstrap-test-suite.js#L13-L37 and https://github.com/cure53/DOMPurify/blob/dd053931337b457da156530c4db0c1d5c92f66a4/test/jsdom-node.js.

**Comment by miggs125** [comment]
@humphd I've started investigating this after you mentioned it yesterday, I can focus on this one but I may have to give away the issue I am currently assigned #273

**Comment by humphd** [comment]
@miggs125 this isn't critical, I just wanted to get it filed for later.  We can loop back on it.

**Comment by humphd** [comment]
We're going to need a fix for this soon, since we've hooked up the sanitizer.  I think we probably need to change how we/DOMPurify is creating the HTML document that gets parsed, so that it doesn't fail when trying to load resources (e.g., img)

```
[ 2019-12-05 11:15:38.669 ] ERROR (30885 on MacBook-Pro.local): Unable to process feed https://ekatdev.wordpress.com/category/SPO600/feed/ for job 1287
    err: {
      "type": "TypeError",
      "message": "Cannot read property 'fetch' of null",
      "stack":
          TypeError: Cannot read property 'fetch' of null
              at PerDocumentResourceLoader.fetch (/Users/humphd/repos/telescope/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
              at HTMLImageElementImpl._attrModified (/Users/humphd/repos/telescope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:39:36)
              at Object.exports.appendAttribute (/Users/humphd/repos/telescope/node_modules/jsdom/lib/jsdom/living/attributes.js:62:11)
              at Object.exports.setAttributeValue (/Users/humphd/repos/telescope/node_modules/jsdom/lib/jsdom/living/attributes.js:218:13)
              at JSDOMParse5Adapter.adoptAttributes (/Users/humphd/repos/telescope/node_modules/jsdom/lib/jsdom/browser/parser/html.js:152:18)
              at JSDOMParse5Adapter.createElement (/Users/humphd/repos/telescope/node_modules/jsdom/lib/jsdom/browser/parser/html.js:73:10)
              at Parser._appendElement (/Users/humphd/repos/telescope/node_modules/parse5/lib/parser/index.js:553:42)
              at areaStartTagInBody (/Users/humphd/repos/telescope/node_modules/parse5/lib/parser/index.js:1519:7)
              at Object.startTagInBody [as START_TAG_TOKEN] (/Users/humphd/repos/telescope/node_modules/parse5/lib/parser/index.js:1725:17)
              at Parser._processToken (/Users/humphd/repos/telescope/node_modules/parse5/lib/parser/index.js:657:55)
    }
```
