### ISSUE TITLE
Vercel fails errors with `Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3650]
In #3649 we are failing a Vercel deployment.  Here is the failure:

```
[20:07:05.380] Cloning github.com/Seneca-CDOT/telescope (Branch: issues/issue-3645, Commit: 1dcd94a)
[20:07:07.713] Cloning completed: 2.333s
[20:07:08.268] Looking up build cache...
[20:07:14.934] Build cache downloaded [78.90 MB]: 6291.893ms
[20:07:14.980] Running "vercel build"
[20:07:15.689] Vercel CLI 28.2.2
[20:07:16.060] Running "install" command: `pnpm install`...
[20:07:17.161] Progress: resolved 1, reused 0, downloaded 0, added 0
[20:07:18.170] Progress: resolved 14, reused 0, downloaded 9, added 0
[20:07:19.172] Progress: resolved 25, reused 0, downloaded 19, added 0
[20:07:20.175] Progress: resolved 34, reused 0, downloaded 29, added 0
[20:07:21.178] Progress: resolved 39, reused 0, downloaded 35, added 0
[20:07:22.178] Progress: resolved 42, reused 0, downloaded 40, added 0
[20:07:23.180] Progress: resolved 44, reused 0, downloaded 42, added 0
[20:07:24.184] Progress: resolved 45, reused 0, downloaded 44, added 0
[20:07:25.187] Progress: resolved 46, reused 0, downloaded 44, added 0
[20:07:26.188] Progress: resolved 46, reused 0, downloaded 45, added 0
[20:07:27.187] Progress: resolved 47, reused 0, downloaded 45, added 0
[20:07:28.945] Progress: resolved 47, reused 0, downloaded 46, added 0
[20:07:30.139] Progress: resolved 48, reused 0, downloaded 46, added 0
[20:07:31.167] Progress: resolved 49, reused 0, downloaded 46, added 0
[20:07:32.167] Progress: resolved 49, reused 0, downloaded 48, added 0
[20:07:33.168] Progress: resolved 107, reused 0, downloaded 84, added 0
[20:07:34.176] Progress: resolved 148, reused 0, downloaded 132, added 0
[20:07:35.181] Progress: resolved 223, reused 0, downloaded 203, added 0
[20:07:36.194] Progress: resolved 261, reused 0, downloaded 242, added 0
[20:07:37.198] Progress: resolved 314, reused 0, downloaded 295, added 0
[20:07:38.214] Progress: resolved 409, reused 0, downloaded 392, added 0
[20:07:38.801] Already up-to-date
[20:07:39.214] Progress: resolved 426, reused 0, downloaded 413, added 0, done
[20:07:39.989] 
[20:07:40.016] Detected Next.js version: 12.1.6
[20:07:40.077] Running "pnpm run build"
[20:07:40.713] 
[20:07:40.713] > @senecacdot/telescope-frontend@3.0.0 build /vercel/path1
[20:07:40.713] > next build && next export
[20:07:40.713] 
[20:07:42.349] Trying to load missing ENV variables from /.env
[20:07:42.350] Trying to load missing ENV variables from /config/env.development
[20:07:42.351] Using NEXT_PUBLIC_WEB_URL=https://telescope-kl9xag0me-humphd.vercel.app
[20:07:42.351] Using NEXT_PUBLIC_IMAGE_URL=https://dev.api.telescope.cdot.systems/v1/image
[20:07:42.351] Using NEXT_PUBLIC_POSTS_URL=https://dev.api.telescope.cdot.systems/v1/posts
[20:07:42.352] Using NEXT_PUBLIC_SSO_URL=https://dev.api.telescope.cdot.systems/v1/auth
[20:07:42.352] Using NEXT_PUBLIC_SEARCH_URL=https://dev.api.telescope.cdot.systems/v1/search
[20:07:42.352] Using NEXT_PUBLIC_FEED_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/feed-discovery
[20:07:42.352] Using NEXT_PUBLIC_STATUS_URL=https://dev.api.telescope.cdot.systems/v1/status
[20:07:42.353] Using NEXT_PUBLIC_GIT_COMMIT=undefined
[20:07:42.353] Using NEXT_PUBLIC_SUPABASE_URL=https://dev.api.telescope.cdot.systems/v1/supabase
[20:07:42.353] Using NEXT_PUBLIC_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
[20:07:42.353] Using NEXT_PUBLIC_DEPENDENCY_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/dependency-discovery
[20:07:42.356] warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[20:07:42.419] info  - Checking validity of types...
[20:07:49.297] error - ESLint: Failed to load plugin 'react' declared in '.eslintrc.js » @senecacdot/eslint-config-telescope': Cannot find module 'eslint-plugin-react' Require stack: - /vercel/path1/__placeholder__.js Referenced from: /vercel/path1/node_modules/.pnpm/@senecacdot+eslint-config-telescope@1.1.0_eslint@7.32.0/node_modules/@senecacdot/eslint-config-telescope/index.js
[20:07:49.301] info  - Creating an optimized production build...
[20:07:49.386] > [PWA] Compile client (static)
[20:07:49.387] > [PWA] Auto register service worker with: /vercel/path1/node_modules/.pnpm/next-pwa@5.4.6_b9348bf848bb7cd32c9b4304596174f6/node_modules/next-pwa/register.js
[20:07:49.387] > [PWA] Service worker: /vercel/path1/public/sw.js
[20:07:49.388] > [PWA]   url: /sw.js
[20:07:49.388] > [PWA]   scope: /
[20:07:49.660] > [PWA] Compile server
[20:07:49.662] > [PWA] Compile server
[20:08:12.959] info  - Compiled successfully
[20:08:12.959] info  - Collecting page data...
[20:08:14.662] info  - Generating static pages (0/5)
[20:08:14.754] info  - Generating static pages (1/5)
[20:08:14.764] info  - Generating static pages (2/5)
[20:08:14.770] info  - Generating static pages (3/5)
[20:08:14.818] info  - Generating static pages (5/5)
[20:08:14.832] info  - Finalizing page optimization...
[20:08:14.836] 
[20:08:14.859] Page                                       Size     First Load JS
[20:08:14.860] ┌ ○ /                                      11 kB           195 kB
[20:08:14.860] ├   /_app                                  0 B             109 kB
[20:08:14.860] ├ ○ /404                                   179 B           109 kB
[20:08:14.860] ├ λ /dependencies                          30.8 kB         245 kB
[20:08:14.860] ├ ○ /error                                 3.53 kB         133 kB
[20:08:14.860] ├ λ /search                                4.66 kB         240 kB
[20:08:14.860] └ ○ /signup                                42.5 kB         194 kB
[20:08:14.860] + First Load JS shared by all              109 kB
[20:08:14.861]   ├ chunks/framework-248ddb2458fac65d.js   42.2 kB
[20:08:14.861]   ├ chunks/main-72922e6a2d43303e.js        31.1 kB
[20:08:14.861]   ├ chunks/pages/_app-716d3698ff453fd9.js  33.4 kB
[20:08:14.861]   ├ chunks/webpack-49e9b42e3e828a11.js     1.78 kB
[20:08:14.861]   └ css/42efb15929f5c757.css               1.57 kB
[20:08:14.861] 
[20:08:14.861] λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
[20:08:14.861] ○  (Static)  automatically rendered as static HTML (uses no initial props)
[20:08:14.862] 
[20:08:16.356] Trying to load missing ENV variables from /.env
[20:08:16.357] Trying to load missing ENV variables from /config/env.development
[20:08:16.358] Using NEXT_PUBLIC_WEB_URL=https://telescope-kl9xag0me-humphd.vercel.app
[20:08:16.358] Using NEXT_PUBLIC_IMAGE_URL=https://dev.api.telescope.cdot.systems/v1/image
[20:08:16.358] Using NEXT_PUBLIC_POSTS_URL=https://dev.api.telescope.cdot.systems/v1/posts
[20:08:16.358] Using NEXT_PUBLIC_SSO_URL=https://dev.api.telescope.cdot.systems/v1/auth
[20:08:16.359] Using NEXT_PUBLIC_SEARCH_URL=https://dev.api.telescope.cdot.systems/v1/search
[20:08:16.359] Using NEXT_PUBLIC_FEED_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/feed-discovery
[20:08:16.359] Using NEXT_PUBLIC_STATUS_URL=https://dev.api.telescope.cdot.systems/v1/status
[20:08:16.359] Using NEXT_PUBLIC_GIT_COMMIT=undefined
[20:08:16.359] Using NEXT_PUBLIC_SUPABASE_URL=https://dev.api.telescope.cdot.systems/v1/supabase
[20:08:16.359] Using NEXT_PUBLIC_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
[20:08:16.360] Using NEXT_PUBLIC_DEPENDENCY_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/dependency-discovery
[20:08:16.362] warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[20:08:16.551] info  - using build directory: /vercel/path1/.next
[20:08:16.558] info  - Copying "static build" directory
[20:08:16.564] info  - No "exportPathMap" found in "/vercel/path1/next.config.js". Generating map from "./pages"
[20:08:16.565] info  - Launching 3 workers
[20:08:16.566] info  - Exporting (0/6)
[20:08:16.566] info  - Copying "public" directory
[20:08:17.329] info  - Exporting (1/6)
[20:08:17.422] info  - Exporting (2/6)
[20:08:17.426] info  - Exporting (4/6)
[20:08:17.824] 
[20:08:17.824] Error occurred prerendering page "/dependencies". Read more: https://nextjs.org/docs/messages/prerender-error
[20:08:17.824] Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
[20:08:17.824] Require stack:
[20:08:17.825] - /vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js
[20:08:17.825] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/composeClasses/index.js
[20:08:17.825] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/BadgeUnstyled.js
[20:08:17.825] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/index.js
[20:08:17.826] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/index.js
[20:08:17.826] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/IconButton/IconButton.js
[20:08:17.826] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/IconButton/index.js
[20:08:17.826] - /vercel/path1/.next/server/pages/dependencies.js
[20:08:17.827] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/require.js
[20:08:17.827] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/load-components.js
[20:08:17.828] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/export/worker.js
[20:08:17.828] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/compiled/jest-worker/processChild.js
[20:08:17.828]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[20:08:17.828]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[20:08:17.829]     at Module.require (internal/modules/cjs/loader.js:974:19)
[20:08:17.829]     at require (internal/modules/cjs/helpers.js:101:18)
[20:08:17.829]     at Object.<anonymous> (/vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js:8:30)
[20:08:17.829]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[20:08:17.830]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[20:08:17.830]     at Module.load (internal/modules/cjs/loader.js:950:32)
[20:08:17.830]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[20:08:17.830]     at Module.require (internal/modules/cjs/loader.js:974:19)
[20:08:17.986] 
[20:08:17.986] Error occurred prerendering page "/search". Read more: https://nextjs.org/docs/messages/prerender-error
[20:08:17.987] Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
[20:08:17.987] Require stack:
[20:08:17.987] - /vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js
[20:08:17.987] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/composeClasses/index.js
[20:08:17.988] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/BadgeUnstyled.js
[20:08:17.988] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/index.js
[20:08:17.988] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/index.js
[20:08:17.989] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/styles/createTheme.js
[20:08:17.989] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/styles/index.js
[20:08:17.989] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/index.js
[20:08:17.989] - /vercel/path1/.next/server/pages/search.js
[20:08:17.990] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/require.js
[20:08:17.990] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/load-components.js
[20:08:17.990] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/export/worker.js
[20:08:17.990] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/compiled/jest-worker/processChild.js
[20:08:17.990]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[20:08:17.991]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[20:08:17.991]     at Module.require (internal/modules/cjs/loader.js:974:19)
[20:08:17.991]     at require (internal/modules/cjs/helpers.js:101:18)
[20:08:17.991]     at Object.<anonymous> (/vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js:8:30)
[20:08:17.991]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[20:08:17.991]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[20:08:17.992]     at Module.load (internal/modules/cjs/loader.js:950:32)
[20:08:17.992]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[20:08:17.992]     at Module.require (internal/modules/cjs/loader.js:974:19)
[20:08:17.992] Error: Export encountered errors on following paths:
[20:08:17.992] 	/dependencies
[20:08:17.993] 	/search
[20:08:17.993]     at /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/export/index.js:398:19
[20:08:17.993]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[20:08:17.993]     at async Span.traceAsyncFn (/vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/trace/trace.js:79:20)
[20:08:17.993] info  - Exporting (6/6)
[20:08:18.005]  ELIFECYCLE  Command failed with exit code 1.
[20:08:18.014] Error: Command "pnpm run build" exited with 1
```

**Comment by DukeManh** [comment]
Looks like it fails on exporting `/dependencies` and `/search` page. One thing the 2 pages have in common is their children have MUIv5 `@mui` imports. I know we want to gradually migrate from MUI v4 but v5, but maybe using both versions at the same time caused the problem? 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/51073515/189007574-4eea7a4d-b505-4d06-b07b-df39febeebe7.png">

**Comment by humphd** [comment]
I need to refresh my memory on what needs to happen for MUI v5, but yeah, we should work to migrate.  CC @cindyledev

**Comment by manekenpix** [comment]
This was fixed in one of the recent dependency fixes.
