### ISSUE TITLE
Elastic search unable to index document with Object for title

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3652]
In the parser service, I notice this log:

```json
{
  "level": 50,
  "time": 1662816844919,
  "pid": 20,
  "hostname": "cb917ab8e9de",
  "error": {
    "stack": "ResponseError: mapper_parsing_exception: [mapper_parsing_exception] Reason: failed to parse field [title] of type [text] in document with id '07ab051ae7'. Preview of field's value: '{$={type=text}}'\n    at onBody (/app/node_modules/.pnpm/@elastic+elasticsearch@7.17.0/node_modules/@elastic/elasticsearch/lib/Transport.js:367:23)\n    at IncomingMessage.onEnd (/app/node_modules/.pnpm/@elastic+elasticsearch@7.17.0/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
    "message": "mapper_parsing_exception: [mapper_parsing_exception] Reason: failed to parse field [title] of type [text] in document with id '07ab051ae7'. Preview of field's value: '{$={type=text}}'",
    "name": "ResponseError",
    "meta": {
      "body": {
        "error": {
          "root_cause": [
            {
              "type": "mapper_parsing_exception",
              "reason": "failed to parse field [title] of type [text] in document with id '07ab051ae7'. Preview of field's value: '{$={type=text}}'"
            }
          ],
          "type": "mapper_parsing_exception",
          "reason": "failed to parse field [title] of type [text] in document with id '07ab051ae7'. Preview of field's value: '{$={type=text}}'",
          "caused_by": {
            "type": "illegal_state_exception",
            "reason": "Can't get text on a START_OBJECT at 1:252"
          }
        },
        "status": 400
      },
      "statusCode": 400,
      "headers": {
        "x-elastic-product": "Elasticsearch",
        "warning": "299 Elasticsearch-7.17.4-79878662c54c886ae89206c685d9f1051a9d6411 \"Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.\"",
        "content-type": "application/json; charset=UTF-8",
        "content-length": "477"
      },
      "meta": {
        "context": null,
        "request": {
          "params": {
            "method": "PUT",
            "path": "/posts/_doc/07ab051ae7",
            "body": "{\"text\":\"A new blog for a new course [two even!], OOP344 and SPO600. It'll probably be just blank text for a while, until I feel like mocking up templates.Until then, lots of programming talk. C++, Assembler, and so forth in ugly plain text.\",\"title\":{\"$\":{\"type\":\"text\"}},\"published\":\"2014-01-11T19:47:00.001Z\",\"author\":\"Matthew Grosvenor\"}",
            "querystring": "",
            "headers": {
              "user-agent": "elasticsearch-js/7.17.0 (linux 5.18.16-100.fc35.x86_64-x64; Node.js v16.17.0)",
              "x-elastic-client-meta": "es=7.17.0,js=16.17.0,t=7.17.0,hc=16.17.0",
              "content-type": "application/json",
              "content-length": "341"
            },
            "timeout": 30000
          },
          "options": {},
          "id": 6067
        },
        "name": "elasticsearch-js",
        "connection": {
          "url": "http://elasticsearch:9200/",
          "id": "http://elasticsearch:9200/",
          "headers": {},
          "deadCount": 0,
          "resurrectTimeout": 0,
          "_openRequests": 23,
          "status": "alive",
          "roles": {
            "master": true,
            "data": true,
            "ingest": true,
            "ml": false
          }
        },
        "attempts": 0,
        "aborted": false
      }
    }
  },
  "msg": "There was an error indexing a post for id 07ab051ae7"
}
```

The post in question is this:

```json
{
  "id": "07ab051ae7",
  "title": "[object Object]",
  "html": "A new blog for a new course [two even!], OOP344 and SPO600. It'll probably be just blank text for a while, until I feel like mocking up templates.<br><br>Until then, lots of programming talk. C++, Assembler, and so forth in ugly plain text.",
  "published": "2014-01-11T19:47:00.000Z",
  "updated": "2014-01-13T04:41:05.000Z",
  "url": "http://compiledsprawl.blogspot.com/2014/01/a-new-blog-for-new-course-two-even.html",
  "guid": "tag:blogger.com,1999:blog-8227432383746499375.post-7258289869849644741",
  "type": "blogpost",
  "feed": {
    "id": "a394d88c0e",
    "author": "Matthew Grosvenor",
    "url": "http://compiledsprawl.blogspot.com/feeds/posts/default/-/open-source",
    "user": "",
    "link": "http://compiledsprawl.blogspot.com/search/label/open-source",
    "etag": "W/\"ce295b9cf3a8ab9fc755faddc8929293b09eaaeee7e6507b637c6557d7c8c7df\"",
    "lastModified": "Tue, 21 Dec 2021 00:07:13 GMT"
  }
}
```

From https://api.telescope.cdot.systems/v1/posts/07ab051ae7.

So it looks like the feed parser is serializing an Object vs. returning a string, and Elastic doesn't like it (it shouldn't).  So why is that post using an `Object` vs. a `string` for the title?

**Comment by humphd** [comment]
This is the original post:

https://compiledsprawl.blogspot.com/2014/01/a-new-blog-for-new-course-two-even.html

Reading the raw feed, I see this:

```xml
<item>
      <guid isPermaLink="false">tag:blogger.com,1999:blog-8227432383746499375.post-7258289869849644741</guid>
      <pubDate>Sat, 11 Jan 2014 19:47:00 +0000</pubDate>
      <atom:updated>2014-01-12T20:41:05.966-08:00</atom:updated>
      <category domain="http://www.blogger.com/atom/ns#">CDOT</category>
      <category domain="http://www.blogger.com/atom/ns#">OOP344</category>
      <category domain="http://www.blogger.com/atom/ns#">open-source</category>
      <title/>
      <description>A new blog for a new course [two even!], OOP344 and SPO600. It'll probably be just blank text for a while, until I feel like mocking up templates.&lt;br /&gt;&lt;br /&gt;Until then, lots of programming talk. C++, Assembler, and so forth in ugly plain text.</description>
      <link>https://compiledsprawl.blogspot.com/2014/01/a-new-blog-for-new-course-two-even.html</link>
      <author>noreply@blogger.com (Gabbo)</author>
      <thr:total>0</thr:total>
    </item>
```

So the title is an empty element, which is probably being turned into `undefined` and then that gets serialized to `[object Object]`.  We should use something like `Untitled` or something in the parser service for this vs. allowing empty titles.

I would say this code isn't working:

https://github.com/Seneca-CDOT/telescope/blob/f4f9582ac16b13f0374be50b410b49b491b940ca/src/api/parser/src/data/post.js#L136-L140

**Comment by RC-Lee** [comment]
Under the error log in `parser`
https://github.com/Seneca-CDOT/telescope/blob/f4f9582ac16b13f0374be50b410b49b491b940ca/src/api/parser/src/utils/indexer.js#L109

I added this:
```js
console.log({title});
```

Here's what turned out in the logs
```console
{ title: { '$': { type: 'text' } } }
```

Maybe this is how blogspot parses their empty titles on their end?

**Comment by humphd** [comment]
What on earth!?  Seems like something to git into in the parser logic.  We shouldn't be getting an Object like this.
