### ISSUE TITLE
TypeError: readingLevel is not a function

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#406]
Seen during a test run on Circle CI:

```
test/inactive-blog-filter.test.js
  ● Redlisted feed checking › should handle empty redlists by resolving with a false value

    expect(received).resolves.toBe()

    Received promise rejected instead of resolved
    Rejected to value: [TypeError: Cannot read property 'readFile' of undefined]

      69 |
      70 |   it('should handle empty redlists by resolving with a false value', async () => {
    > 71 |     await expect(inactiveFilter.check(redlist[0].url, pathToMockRedList)).resolves.toBe(false);
         |           ^
      72 |   });
      73 | });
      74 |

      at expect (node_modules/expect/build/index.js:138:15)
      at Object.it (test/inactive-blog-filter.test.js:71:11)

  ● Testing of update() › should not redlist active blogs

    TypeError: Cannot read property 'readFile' of undefined

      74 |
      75 |   // Read the feeds list file
    > 76 |   return fsPromises.readFile(feedsPath, 'utf-8').then(async lines => {
         |                     ^
      77 |     // Divide the file into separate lines
      78 |     const feedUrlList = lines
      79 |       .split(/\r?\n/)

      at Object.update (src/backend/utils/inactive-blog-filter.js:76:21)
      at Object.it (test/inactive-blog-filter.test.js:133:8)

  ● Testing of update() › should redlist inactive blogs

    TypeError: Cannot read property 'readFile' of undefined

      74 |
      75 |   // Read the feeds list file
    > 76 |   return fsPromises.readFile(feedsPath, 'utf-8').then(async lines => {
         |                     ^
      77 |     // Divide the file into separate lines
      78 |     const feedUrlList = lines
      79 |       .split(/\r?\n/)

      at Object.update (src/backend/utils/inactive-blog-filter.js:76:21)
      at Object.it (test/inactive-blog-filter.test.js:149:8)

  ● Testing of update() › should redlist invalid or dead blogs

    TypeError: Cannot read property 'readFile' of undefined

      74 |
      75 |   // Read the feeds list file
    > 76 |   return fsPromises.readFile(feedsPath, 'utf-8').then(async lines => {
         |                     ^
      77 |     // Divide the file into separate lines
      78 |     const feedUrlList = lines
      79 |       .split(/\r?\n/)

      at Object.update (src/backend/utils/inactive-blog-filter.js:76:21)
      at Object.it (test/inactive-blog-filter.test.js:168:8)

(node:1258) UnhandledPromiseRejectionWarning: TypeError: readingLevel is not a function
(node:1258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

**Comment by Silvyre** [comment]
Looking into this.

**Comment by humphd** [comment]
This turns out to be an issue of node versions.  We can improve things by requiring that our node `engine` be new enough to support `fs.promises`.

**Comment by Silvyre** [comment]
Should we additional set [`engine-strict=true`](https://docs.npmjs.com/misc/config#engine-strict) in [`.npmrc`](https://github.com/Seneca-CDOT/telescope/blob/master/.npmrc) to more strongly enforce this?

**Comment by humphd** [comment]
Let's start with just warning, and we can escalate from there if necessary.

**Comment by Silvyre** [comment]
On it.

**Comment by humphd** [comment]
Another data point for you:

```
npm WARN notsup Unsupported engine for spam-filter@1.1.1: wanted: {"node":"8","npm":"5"} (current: {"node":"12.13.1","npm":"6.12.1"})
npm WARN notsup Not compatible with your version of node/npm: spam-filter@1.1.1
```

We are going to have some version issues to deal with for using LTS.  cc @manekenpix, who is hitting this in Circle CI, and @shmooey who is working on version updates, and might find this interesting.

**Comment by cindyledev** [comment]
Reopening this as #412 doesn't resolve this issue

**Comment by humphd** [comment]
For the `readingLevel` issue, I think it can be fixed like so:

```diff
diff --git a/src/backend/utils/reading-level.js b/src/backend/utils/reading-level.js
index 0317f5a..4c9858a 100644
--- a/src/backend/utils/reading-level.js
+++ b/src/backend/utils/reading-level.js
@@ -26,7 +26,7 @@
   error: 'Either no sentences or words, please enter valid text' }
 */

-const readingLevel = require('reading-level');
+const { readingLevel } = require('reading-level');

 module.exports = async function(content) {
   return readingLevel(content, 'full');
```

**Comment by Silvyre** [comment]
I am unassigning myself from this issue, as
1. I believe my role its resolution is complete, and
1. I suspect my assignment may be keeping others from investigating further

Ideally, some input from @jordanhui19 (the author and sole contributor of [`reading-level.js`](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/reading-level.js) and [`reading-level.test.js`](https://github.com/Seneca-CDOT/telescope/blob/master/test/reading-level.test.js) could be acquired.

**Comment by Silvyre** [comment]
With the removal of reading-level.js and reading-level.test.js, I believe that this issue can be considered resolved. Thoughts, @humphd?

**Comment by humphd** [comment]
Agreed.
