### ISSUE TITLE
CI Test failures in feed-worker.js

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#458]
I keep [running into these test failures](https://travis-ci.org/Seneca-CDOT/telescope/jobs/620930584?utm_medium=notification&utm_source=github_status), and it might be due to improved `try/catch` error handling in the feed worker's processor function:

```
FAIL  test/feed-worker.test.js
  ● testing the worker callback function › should pass with a valid ATOM feed URI
    expect(received).resolves.toBeTruthy()
    Received promise rejected instead of resolved
    Rejected to value: [TypeError: Cannot read property 'fetch' of null]
      13 | 
      14 |   it('should pass with a valid ATOM feed URI', async () => {
    > 15 |     await expect(feedWorker.workerCallback(job1)).resolves.toBeTruthy();
         |           ^
      16 |   });
      17 | 
      18 |   it('should fail with an invalid ATOM feed URI should error', async () => {
      at expect (node_modules/expect/build/index.js:138:15)
      at Object.<anonymous> (test/feed-worker.test.js:15:11)
  ● testing the worker callback function › should fail with an invalid ATOM feed URI should error
    RequestError: Error: Invalid URI "c3ho.blogspot.com/feeds/posts/default/-/open-source?alt=rss"
      at new RequestError (node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.Object.<anonymous>.Request.init (node_modules/request/request.js:273:17)
      at Request.RP$initInterceptor [as init] (node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (node_modules/request/request.js:127:8)
      at request (node_modules/request/index.js:53:10)
      at Function.get (node_modules/request/index.js:61:12)
  ● testing the worker callback function › should pass with a valid RSS feed URI
    expect(received).resolves.toBeTruthy()
    Received promise rejected instead of resolved
    Rejected to value: [TypeError: Cannot read property 'fetch' of null]
      21 | 
      22 |   it('should pass with a valid RSS feed URI', async () => {
    > 23 |     await expect(feedWorker.workerCallback(job3)).resolves.toBeTruthy();
         |           ^
      24 |   });
      25 | 
      26 |   it('should fail with an invalid RSS feed URI', async () => {
      at expect (node_modules/expect/build/index.js:138:15)
      at Object.<anonymous> (test/feed-worker.test.js:23:11)
  ● testing the worker callback function › should fail with an invalid RSS feed URI
    RequestError: Error: Invalid URI "c3ho.blogspot.com/feeds/posts/default/-/open-source"
      at new RequestError (node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.Object.<anonymous>.Request.init (node_modules/request/request.js:273:17)
      at Request.RP$initInterceptor [as init] (node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (node_modules/request/request.js:127:8)
      at request (node_modules/request/index.js:53:10)
      at Function.get (node_modules/request/index.js:61:12)
  ● testing the worker callback function › should fail by passing an IP address instead of a URI
    RequestError: Error: Invalid URI "128.190.222.135"
      at new RequestError (node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.Object.<anonymous>.Request.init (node_modules/request/request.js:273:17)
      at Request.RP$initInterceptor [as init] (node_modules/request-promise-core/configure/request2.js:45:29)
      at new Request (node_modules/request/request.js:127:8)
      at request (node_modules/request/index.js:53:10)
      at Function.get (node_modules/request/index.js:61:12)
```

I don't think these tests are doing what we expect, and they shouldn't be causing failures all the time.  cc @ragnarokatz, who was one of the ones who worked on them.

**Comment by ragnarokatz** [comment]
@humphd I'll take a look at this.

**Comment by humphd** [comment]
My change in #466 fixed these for me, not 100% sure why.  I suspect our tests aren't doing the right thing with failed promises, and it's getting tripped by the errors thrown from DOMPurify.

**Comment by ragnarokatz** [comment]
@humphd yup. After pulling down the latest changes from upstream master, I can confirm this is fixed on my end. I guess the troublemaker was indeed the `DOMpurify` module.

I'm opening up 2 more issues based on this one:
1. Seeing that we only have one simple test case in `sanitize-html.test.js`, we should add more to catch these errors on a unit test level, not when the errors get carried over all the way to `worker.js`.
2. The tests in `feed-worker.test.js` have gone out of date. Instead of going out to the web to get real responses, I have mocked up the responses using our `nock` and `fixture` modules in a fashion similar to `feed-parser.test.js`

I'll be linking the issues shortly.

**Comment by ragnarokatz** [comment]
The key error message was this: `Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

My guess is that it was referring to these lines:
```
return await Promise.all(
      posts.map(async post => {
        // TODO: run this through text parser
        const sanitizedHTML = await sanitizeHTML.run(post.description);
```

when `sanitizeHTML.run` errors, `Promise.all` didn't have a `catch` to handle it.

**Comment by humphd** [comment]
@ragnarokatz interesting.  I'm unclear why the enclosing `try/catch` wouldn't be enough to deal with that...

**Comment by humphd** [comment]
Let's close this, and follow-up in your other issues.  Thanks for your research.
