### ISSUE TITLE
Missing docker deps

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#705]
**What happened**:

When we build the frontend app in our Docker container, we have a few failures, I think due to missing deps:

```
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c ./configure --disable-shared --prefix="/telescope/src/frontend/node_modules/cwebp-bin/vendor" --bindir="/telescope/src/frontend/node_modules/cwebp-bin/vendor"
configure: error: in `/tmp/0f6766ab-603e-43fc-9e52-53b5dad36ad4':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for style of include used by make... none
checking for gcc... no
checking for cc... no
checking for cl.exe... no

    at /telescope/src/frontend/node_modules/bin-build/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)

> mozjpeg@6.0.1 postinstall /telescope/src/frontend/node_modules/mozjpeg
> node lib/install.js

  ⚠ spawn /telescope/src/frontend/node_modules/mozjpeg/vendor/cjpeg ENOENT
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: autoreconf: not found


    at /telescope/src/frontend/node_modules/bin-build/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)

/bin/sh: lscpu: not found

```

None of these seem fatal, but I wonder if we should try to fix?

**What should have happened**:

It would be nice if our build didn't error.  If it's possible to do this without importing a ton of things to bloat our container, it would be nice.

**How to reproduce it (as precise as possible)**:

```
docker-compose up --build
```

**Environment**:

- OS: macOS

cc @raygervais

**Comment by humphd** [comment]
This has never been an issue, closing.
